spring.datasource.url=jdbc:mysql://avnadmin:@mysql-2d5b5917-sc858889-29d2.l.aivencloud.com:23281/defaultdb?ssl-mode=REQUIRED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_XBzo66f9qiDXWxv-r3S
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#spring.main.allow-circular-references=true

spring.mail.host=smtp.gmail.com
spring.mail.username=********@gmail.com
spring.mail.password=ylyi rrdm piut smbm # app password
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

rupee.sign=${RUPEE_SIGN:&#8377;}
